### PR TITLE
add method to allow user to play again

### PR DESCRIPTION
**Pull request by cito125**
Add method that allows user to play again. Method called `wantToPlayAgain()`. Also changed changed `while` to `do-while` loop in `Hangman` psvm.

### CODE REVIEW

**Comment by jsjrobotics** [comment]
@cito125 You are supposed to push your answers to your own repo, but well done figuring out how to create a pull request

**Comment by cito125** [comment]
Does this mean I need to resubmit?

On Wed, Aug 31, 2016 at 10:13 AM, Jonathan Johnson <notifications@github.com

**Comment by jsjrobotics** [comment]
Yes.

**Comment by cito125** [comment]
Hi Ariel,



This is regarding our Pay It Forward (“PIF”) Agreement which wholly
delineates the terms and conditions of my enrollment in Coalition for
Queens (“C4Q”) Access Code program.  I am particularly concerned with
repeated requests from Vemo—your third-party lender, to submit a “Status
Change Request” form (“Vemo form”). See Exhibit 1, attached.  The language
contained in the Vemo form contradicts the terms and conditions that I
agreed to in our PIF Agreement, since it is essentially requesting that I
apply for a “payment deferment.” Vemo’s latest request was made on December
20, 2017. See Exhibit 2, attached. This despite my effort, in a December 10
th email to them, explaining that I would not submit the form since its
language and purpose contradicts the terms and conditions contained in my
PIF Agreement with C4Q. See Exhibit 3, attached. I understand that Vemo is
working on your behalf.  Notably, Vemo has been CC'd in this communication.
Therefore, I respectfully request that you confer with Vemo and confirm
that, based on the PIF Agreement, I am not obligated to submit the “Status
Change Request” form in its current form.



As parties to the PIF agreement, we both acknowledged that “there are no
upfront costs or tuition for participation in the Access Code program.”
See PIF Agreement, page 1, Acnowledgements Section. Moreover, Vemo is not a
party to this PIF Agreement and certainly not as a lender. This is
understandable since I never entered into a loan agreement with Vemo.
Therefore, to be clear, my financial obligation is to C4Q only.  Any
document requests that do not respect the original terms of our agreement
are invalid and unreasonable.



The PIF Agreement addresses when I am obligated to comply with document
requests from C4Q or its third-party lenders to secure my obligations to
C4Q (referred to as the “Collateral Documentation”).  See PIF Agreement,
page 2, §4.  The request must be “reasonable.”  Since the language in
Vemo’s Status Change Request form contradicts the terms and conditions of
the PIF Agreement—there are no payment obligations to defer, I insist the
request to fill out the form going forward is unreasonable.



Please take a moment to read the December 10th, 2017 email I sent to Vemo
in which I lay out my understanding of the PIF Agreement; this summarizes
why I will not apply for a payment deferment via Vemo’s form. See Exhibit
3, attached. Vemo’s communications also imply that I am obligated to them
to demonstrate my monthly income. See Exhibit 4, attached.  Again, this
request is not in accordance with our PIF Agreement. Any “collateral
documentation” that is requested of me should conform to the PIF
Agreement’s. In order to trigger any payment obligations on my behalf to
C4Q, the following three elements must exist, as defined in the PIF
Agreement:



·       Source of Payments

·       Covered Employment

·       Covered Period



I respectfully request that you confirm my understanding of the PIF
Agreement as laid out in my December 10th, 2017 email to Vemo.  See Exhibit
3, attached.  Also, please reach out to Vemo and inform them that the
language in their document requests must conform and be tailored to the
actual obligations contained in our PIF Agreement.  Moreover, I am
concerned that Vemo has inserted itself into our contractual relationship
as a “Lender” in a manner that I never agreed to.  This is clear
particularly since they are nowhere mentioned in, nor are they signatories
to our PIF Agreement.  Going forward, please ensure that “Collateral
Documentation” requests from third-parties respect the PIF Agreement as we
agreed to.



Thank you for your consideration and assistance.



Sincerely,



Andres Arango



Attachments

·       Exhibit 1—Vemo Status Change Request Form

·       Exhibit 2—Vemo Dececember 20, 2017 email

·       Exhibit 3—December 10, 2017 Email from Andres to Vemo

·       Exhibit 4—Vemo November 6, 2017 email

**Pull request closed without merging**
